[package]
name = "rs-pedalboard"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"
path = "src/bin/server/server.rs"

[[bin]]
name = "client"
path = "src/bin/client/client.rs"

[dependencies]
log = "0.4.26"
cpal = {version = "0.15.3", features=["jack"]}
simplelog = "0.12.2"
ringbuf = "0.4.7"
regex = "1.11.1"
strum = "0.27"
strum_macros = "0.27"
realfft = "3.4.0"
