[package]
name = "rs-pedalboard"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"
path = "src/bin/server/server.rs"

[[bin]]
name = "client"
path = "src/bin/client/client.rs"

[dependencies]
log = {version = "0.4.26", features=["release_max_level_warn"]}
cpal = {version = "0.15.3", features=["jack"]}
ringbuf = "0.4.7"
